### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by merwok** [farhan0581/django-admin-autocomplete-filter#1]
This is fantastic!

**Comment by farhan0581** [comment]
Glad you liked it !

**Comment by paultiplady** [comment]
@farhan0581 have you considered upstreaming this? The devs have expressed interest in this feature: https://code.djangoproject.com/ticket/29111

**Comment by farhan0581** [comment]
Yes I was, but I was working on the Media class bug before giving a pr, was quite busy these days, so couldn't get time.

**Comment by merwok** [comment]
It would be great to have this built-in!
Especially if the filters follow the standard style i.e. `list_filters = [("field", AutocompleteFilter)]` instead of writing subclasses.
