### ISSUE TITLE
empty Media class has to be specified

### ISSUE THREAD

**Issue by macolo** [farhan0581/django-admin-autocomplete-filter#10]
According to the docs: https://github.com/farhan0581/django-admin-autocomplete-filter/blob/master/README.md#usage

```
    '''
       defining this class is required for AutocompleteFilter
       it's a bug and I am working on it.
    '''
```

**Comment by pcraciunoiu** [comment]
Seems like it's just updating the README that's left, then this can be closed?

**Comment by merwok** [comment]
As soon as one of us makes a PR! :slightly_smiling_face:
