### ISSUE TITLE
Overriding get_queryset_for_field doesn't change dropdown values

### ISSUE THREAD

**Issue by IvanAnishchuk** [farhan0581/django-admin-autocomplete-filter#14]
I guess it has to do with the way autocomplete data is retrieved from admin api but the fact remains. Maybe there's some way to add filter params to autocomplete api calls or maybe it has to be hacked in django itself. It would be great to explore if it's possible at all.

**Comment by farhan0581** [comment]
Yeah I use custom view sometimes for the api call.
Will try to release the feature in next release as soon as possible.

**Comment by farhan0581** [comment]
check out the latest code, it might be useful for you.
