### ISSUE TITLE
The filter UI gives jquery error when tried with django2.2

### ISSUE THREAD

**Issue by antsmc2** [farhan0581/django-admin-autocomplete-filter#16]
I kept getting the attached error when testing this with django version 2.2. However, I had to downgrade to 2.1 for it to work. Seems to work well for versions 2.0 and 2.1
<img width="1425" alt="Screenshot 2019-07-15 at 19 57 26" src="https://user-images.githubusercontent.com/1122909/61258367-f44adf00-a73a-11e9-8f7c-d6b7bb6a1906.png">

**Comment by merwok** [comment]
I think #15 addresses this! :slightly_smiling_face:
