### ISSUE TITLE
$ is not a function

### ISSUE THREAD

**Issue by ironlion** [farhan0581/django-admin-autocomplete-filter#19]
TypeError: $ is not a function in autocomplete_filter_qs.js:8:3 for Django 2.2.2

**Comment by ironlion** [comment]
sorry )

**Comment by spumer** [comment]
Same issue here.

Firefox 70

![изображение](https://user-images.githubusercontent.com/735150/68046001-a3b4bd00-fcfc-11e9-89db-a316cb680422.png)

![изображение](https://user-images.githubusercontent.com/735150/68045867-57697d00-fcfc-11e9-9117-1e62ddd71a76.png)

**Comment by spumer** [comment]
@farhan0581 can you publish new version on PyPi since https://github.com/farhan0581/django-admin-autocomplete-filter/pull/24 merged?
