### ISSUE TITLE
How to use calculate value when using in Django >= 2.2

### ISSUE THREAD

**Issue by vit1251** [farhan0581/django-admin-autocomplete-filter#22]
I use autocomplete plugin and receive object model instead field value. How to specify in filter class field for show.

![изображение](https://user-images.githubusercontent.com/110534/63136102-11442d80-bfd9-11e9-98f0-d464f12db3bd.png)

**Comment by farhan0581** [comment]
You can specify `__str__` method in your respective model to get the string representation for the object.
