### ISSUE TITLE
ModuleNotFoundError: No module named 'admin_auto_filters.views'

### ISSUE THREAD

**Issue by vanessa** [farhan0581/django-admin-autocomplete-filter#25]
In my installation folder there's only `apps.py` and `filters.py`. Maybe it's because it's pulling from `dev` branch?

![image](https://user-images.githubusercontent.com/23136832/67174545-c360f280-f398-11e9-8456-378c8657c544.png)

**Comment by merwok** [comment]
`dev` branch is well behind `master`, I guess the author used it in a previous workflow but not any more!

Is there any reason that you’re not installing a release from PyPI using pip?

**Comment by vanessa** [comment]
@merwok Hi, thanks for reaching out. I actually installed from PyPI, and the package came like this. Here's the line in my requirements file:
```
django-admin-autocomplete-filter==0.3
```

**Comment by merwok** [comment]
Ah!  Then I don’t know why the views module isn’t there.  Source code seems ok.

**Comment by merwok** [comment]
Both the sdist and the wheel do not contain views!  Weird given that `setup.py` uses `setuptools.find_packages` which should collect all submodules in a package.

`views.py` seems a little weird `from testing.models import *`, but from memory setuptools doesn’t check for correctness so it’s weird.

**Comment by merwok** [comment]
I cloned the repo and ran `python setup.py -vvv bdist_wheel`, the views module was copied, so I can’t explain the problem with the distributions on PyPI.  Could have been a temporary issue, or a build from the wrong commit, or something else.  Bumping the version number and re-releasing dists should avoid the issue (note: using [twine](https://packaging.python.org/tutorials/packaging-projects/#uploading-the-distribution-archives) is a lot nicer than `python setup.py sdist upload`)
