### ISSUE TITLE
The change in Django 3.2 to consider limit_choices_to has broken this filter.

### ISSUE THREAD

**Issue by ndunn219** [farhan0581/django-admin-autocomplete-filter#53]
When opening the select, the choices don't show up due to this error:
```
'ManyToOneRel' object has no attribute 'get_limit_choices_to'
```

**Comment by erwinfeser** [comment]
+1

**Comment by MDziwny** [comment]
Seems linked: https://code.djangoproject.com/ticket/32619

**Comment by n1k0** [comment]
Let me voice my +1 out loud :)

**Comment by MDziwny** [comment]
There is a workaround:

``` python
from django.db import models

class ModelA(models.Model):
    pass

class ModelB(models.Model):
    model_a = models.ForeignKey(to=ModelA, related_name="models_b")

class NonWorkingAutocompleteWithDj32(AutocompleteFilter):
    """ Autocomplate in the admin of model B """"
    title = _("Model A")
    field_name = "model_a"


class WorkingAutocompleteWithDj32(AutocompleteFilter):
    """ Autocomplate in the admin of model B """"
    title = _("Model A")
    rel_model = ModelA
    field_name = "models_b"
    parameter_name = "model_a"
```

**Comment by ndunn219** [comment]
> There is a workaround:

This filtered correctly for me, but it then changes the filter field to an incorrect value (i.e., not the selection that it's being filtered on).

**Comment by MDziwny** [comment]
> it then changes the filter field to an incorrect value

Oh! You're right, I didn't notice it before, thanks :/

**Comment by MDziwny** [comment]
I've opened a PR with a fix, but there is no tests yet and I'm not sure I will have time to add some.
