### ISSUE TITLE
Doesn't work with primary_key fields at least on Django 3.2

### ISSUE THREAD

**Issue by int-ua** [farhan0581/django-admin-autocomplete-filter#58]
Didn't test on previous version, but with Django 3.2 primary key fields are of `DeferredAttribute` class that doesn't have `get_queryset` method, both for integer `AutoField` and string `CharField`.

Trying to figure out if there are workarounds for this. Also, it doesn't work with Grappelli 2.15.1 on Django 3.2 even with non-PK fields, see https://github.com/sehmaschine/django-grappelli/issues/963

**Comment by MDziwny** [comment]
Did you try with this fix: https://github.com/farhan0581/django-admin-autocomplete-filter/pull/57 ?
Unfortunately, it's not yet available on pypi but you can test it by installing with the git repo instead of the pypi package.

**Comment by int-ua** [comment]
Re-tested it without Grappelli and it works, thank you :+1: 

Now we'll just have to find a fix for that Grappelli issue.
