### ISSUE TITLE
New release on Pypi

### ISSUE THREAD

**Issue by MDziwny** [farhan0581/django-admin-autocomplete-filter#59]
Hello,

The current release available on pypi (0.6.1) doesn't work with django 3.2.
The issue has been fixed in #57.

When can we expect a new release? Can we do something to ease the next release?
In #57, we can see that some people are waiting for it.

**Comment by si14** [comment]
hey @farhan0581 , is there a chance this can be looked on? I saw you mentioned you had a personal emergency, I hope you are well.

**Comment by farhan0581** [comment]
I have release the latest version on pypi (version 0.7)

**Comment by MDziwny** [comment]
Thank you @farhan0581 !
