### ISSUE TITLE
Custom search viewset doesn't function as documented in Django >= 3.2

### ISSUE THREAD

**Issue by maddencs** [farhan0581/django-admin-autocomplete-filter#64]
You can replicate the issue by setting `Django==3.2` in `requirements.txt` and running the tests. The following exception gets raised:

```python
TypeError: FoodsThatAreFavorites() received an invalid keyword 'model_admin'. as_view only accepts arguments that are already attributes of the class.
```

**Comment by KaktusOnFire** [comment]
I have the same problem:
`TypeError: CustomSearchView() received an invalid keyword 'model_admin'. as_view only accepts arguments that are already attributes of the class.`

**Comment by KaktusOnFire** [comment]
@maddencs how did you resolved this problem?
