### ISSUE TITLE
0.3 Release Timeline

### ISSUE THREAD

**Issue by jhnbkr** [farhan0581/django-admin-autocomplete-filter#8]
This is a question not an issue.

I am using 0.2 from pypi in a project. I noticed the field_pk was hardcoded to id and began the process of forking/creating a PR.

I then noticed this was patched by @Maks3w in https://github.com/farhan0581/django-admin-autocomplete-filter/commit/67f92fb2738969f3aafc4c89bb95d90946659638

I am currently pointing my virtualenv requirements to the repo directly. Just curious when a new package will be released on pypi.

Thanks :)

**Comment by dwasyl** [comment]
Just ran into this same issue, any idea if you can issue a new release @farhan0581 ?

**Comment by farhan0581** [comment]
I was a little busy but will try my best to upload it by tomorrow.

**Comment by jhnbkr** [comment]
Bump, any update on this @farhan0581?

**Comment by IvanAnishchuk** [comment]
Yeah, maybe there's anything we could do to help? @farhan0581 Review something, clean something up or, perhaps, debug some outstanding issues? Unreleased changes contain a few things I need for my project and I would rather contribute here than go around forking stuff.

**Comment by farhan0581** [comment]
0.3 version released.

**Comment by merwok** [comment]
Could you create git tags matching the PyPI tags?
It would help people (and tools such as dependabot) for checking differences between versions :)

A changelog text file would also be great!

**Comment by ulgens** [comment]
@farhan0581 Tags would be really nice :slightly_smiling_face: I have an issue with 0.3 and i'm trying to debug it, but finding no reference to versions on repo makes it harder than it should be.
